[package]
name = "kvs"
version = "0.1.0"
authors = ["Lannnnh <15997426361@sina.cn>"]
description = "A key-value store"
edition = "2021"

[dependencies]

[dev-dependencies]

[[bench]]
name = "engine_bench"
harness = false